AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ClientId:
    Type: String
    Default: "423623843304"
    Description: "The AWS account ID that owns the role."
  
  RoleName:
    Type: String
    Default: "LambdaExecutionRole3"
    Description: "The name of the IAM role for the Lambda function."

  Timeout:
    Type: Number
    Default: 10
    Description: "The timeout for the Lambda function in seconds."

  ApiGatewayName:
    Type: String
    Default: "StarkApi"
    Description: "The name of the API Gateway."

Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Runtime: 'python3.12'
      Role: !Sub 'arn:aws:iam::${ClientId}:role/${RoleName}'
      Handler: 'index.handler'
      Timeout: !Ref Timeout
      Code:
        S3Bucket: 'stark-bucket-for-lambda'
        S3Key: 'lambda_resources.zip'
      Environment:
        Variables:
          PRIVATE_KEY: 'PRIVATE_KEY'
          PROJECT_ID: 'PROJECT_ID'

  ApiGateway:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Ref ApiGatewayName

  ApiGatewayResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: 'webhook'
      RestApiId: !Ref ApiGateway

  ApiGatewayMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: 'NONE'
      HttpMethod: 'POST'
      ResourceId: !Ref ApiGatewayResource
      RestApiId: !Ref ApiGateway
      Integration:
        IntegrationHttpMethod: 'POST'
        Type: 'AWS_PROXY'
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations'
      MethodResponses:
        - StatusCode: '200'

  ApiGatewayDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn: ApiGatewayMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: 'prod'

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref LambdaFunction
      Principal: 'apigateway.amazonaws.com'